<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-e44360b8a8db1e130c7792fece1c8032.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-contrib/fontawesome6-6.7.2/latex-fontsize.css" rel="stylesheet"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.3">

  <meta name="author" content="Rizqy Amelia Zein">
  <meta name="dcterms.date" content="2026-05-01">
  <title>Statistik Dasar dalam Penelitian Psikologi – ANOVA Faktorial</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-14c7313e0bd1a6ac1391ac8d6dd3db46.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">ANOVA Faktorial</h1>
  <p class="subtitle">Statistik Dasar dalam Penelitian Psikologi</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rizqy Amelia Zein 
</div>
        <p class="quarto-title-affiliation">
            <a href="https://psikologi.unair.ac.id/dosen-rizqy-amelia-zein/"><em>Departemen Psikologi, Universitas Airlangga</em></a>
          </p>
    </div>
</div>

  <p class="date">2026-05-01</p>
</section>
<section id="outline" class="slide level2">
<h2><em>Outline</em></h2>
<ul>
<li>Mengapa ANOVA faktorial, bukan ANOVA satu jalur terpisah?</li>
<li>Desain faktorial dan notasi</li>
<li><em>Main effects</em> dan <em>interaction effects</em></li>
<li>Partisi varians dalam desain faktorial</li>
<li>Implementasi di jamovi</li>
<li><em>Effect size</em> (η² dan ω²)</li>
<li><em>Post-hoc tests</em></li>
<li>Asumsi dan uji asumsi</li>
<li><em>A priori</em> analisis <em>power</em></li>
</ul>
</section>
<section>
<section id="mengapa-anova-faktorial" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Mengapa ANOVA faktorial?</h1>

</section>
<section id="keterbatasan-anova-satu-jalur" class="slide level2">
<h2>Keterbatasan ANOVA satu jalur</h2>
<p>Bayangkan Alfonso ingin meneliti dua faktor sekaligus: <strong>jenis makanan</strong> (3 level) dan <strong>jenis musik</strong> (2 level) yang diberikan pada kucing. Ia bisa saja menjalankan dua ANOVA satu jalur terpisah:</p>
<ul>
<li>ANOVA 1: efek jenis makanan pada durasi membaca</li>
<li>ANOVA 2: efek jenis musik pada durasi membaca</li>
</ul>
<p><strong>Masalahnya ada tiga:</strong></p>
<ol type="1">
<li><strong>Inflasi <em>Type I error</em></strong>: dua uji independen menggandakan peluang <em>false positive</em></li>
<li><strong>Kehilangan informasi</strong>: apakah efek musik bergantung pada makanan yang diberikan? ANOVA terpisah tidak bisa menjawab ini</li>
<li><strong>Inefisiensi</strong>: satu analisis faktorial lebih <em>powerful</em> karena menggunakan seluruh data untuk setiap estimasi efek</li>
</ol>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>ANOVA faktorial memungkinkan kita menguji <em>main effects</em> dari setiap faktor dan — yang paling penting — <em>interaction effect</em> di antara keduanya, dalam satu analisis yang terintegrasi.</strong></p>
</div>
</div>
</div>
</section>
<section id="apa-itu-desain-faktorial" class="slide level2">
<h2>Apa itu desain faktorial?</h2>
<p>Desain faktorial adalah desain penelitian di mana setiap partisipan mendapatkan <strong>kombinasi perlakuan dari dua atau lebih faktor</strong>, sehingga kita dapat mempelajari efek masing-masing faktor dan interaksinya.</p>
<p><strong>Terminologi:</strong></p>
<ul>
<li><strong>Faktor (<em>factor</em>)</strong>: variabel independen yang dimanipulasi (mis. jenis musik, jenis makanan)</li>
<li><strong>Level</strong>: kategori dalam satu faktor (mis. klasik vs campursari = 2 level)</li>
<li><strong>Sel (<em>cell</em>)</strong>: satu kombinasi spesifik dari semua faktor</li>
</ul>
<p><strong>Notasi desain:</strong> jumlah level setiap faktor dipisahkan tanda ×</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Desain</th>
<th>Artinya</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2 × 2</td>
<td>2 faktor, masing-masing 2 level = 4 sel</td>
</tr>
<tr class="even">
<td>3 × 2</td>
<td>2 faktor, 3 dan 2 level = 6 sel</td>
</tr>
<tr class="odd">
<td>2 × 3 × 2</td>
<td>3 faktor = 12 sel</td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="studi-alfonso-desain-3-2" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Studi Alfonso: desain 3 × 2</h1>

</section>
<section id="konteks-penelitian-alfonso" class="slide level2">
<h2>Konteks penelitian Alfonso</h2>
<p>Alfonso ingin mengetahui apakah jenis makanan dan jenis musik yang diperdengarkan memengaruhi <strong>durasi membaca kucing</strong> (dalam detik).</p>
<p><strong>Faktor dan levelnya:</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Faktor A: Jenis Makanan</strong> (3 level)</p>
<ul>
<li><em>Dry food</em></li>
<li><em>Wet food</em></li>
<li><em>Raw food</em></li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Faktor B: Jenis Musik</strong> (2 level)</p>
<ul>
<li>Musik klasik (<em>Frühlingsstimmen</em> — Strauss II)</li>
<li>Musik campursari (<em>Sewu Kutho</em> — Didi Kempot)</li>
</ul>
</div></div>
<p>Setiap kucing secara acak dialokasikan ke <strong>satu</strong> dari 6 sel (3 × 2 = 6 kombinasi).</p>
<p>Dataset: <a href="..\docs/materials/kucing-membaca.omv"><strong>kucing-membaca.omv</strong></a></p>
</section>
<section id="tabel-desain-3-2" class="slide level2">
<h2>Tabel desain 3 × 2</h2>
<p>Setiap sel berisi <em>mean</em> durasi membaca kucing pada kombinasi perlakuan tersebut:</p>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;">Musik Klasik</th>
<th style="text-align: center;">Musik Campursari</th>
<th style="text-align: center;"><strong>Total (baris)</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><em>Dry food</em></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{11}\)</span> = 0.300</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{12}\)</span> = 0.600</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{1\cdot}\)</span> = 0.450</td>
</tr>
<tr class="even">
<td style="text-align: center;"><em>Wet food</em></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{21}\)</span> = 0.400</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{22}\)</span> = 1.033</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{2\cdot}\)</span> = 0.716</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><em>Raw food</em></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{31}\)</span> = 1.467</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{32}\)</span> = 1.500</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{3\cdot}\)</span> = 1.483</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>Total (kolom)</strong></td>
<td style="text-align: center;"><span class="math inline">\(\mu_{\cdot1}\)</span> = 0.722</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{\cdot2}\)</span> = 1.044</td>
<td style="text-align: center;"><span class="math inline">\(\mu_{\cdot\cdot}\)</span> = 0.833</td>
</tr>
</tbody>
</table>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p><em>Mean</em> baris (<em>row means</em>) merangkum efek utama jenis makanan. <em>Mean</em> kolom (<em>column means</em>) merangkum efek utama jenis musik. <em>Mean</em> sel individual memungkinkan kita mendeteksi interaksi.</p>
</div>
</div>
</div>
</section>
<section id="memeriksa-desain-crosstabs" class="slide level2">
<h2>Memeriksa desain: <em>crosstabs</em></h2>
<p>Sebelum analisis, periksa apakah desain seimbang (<em>balanced</em>):</p>
<ol type="1">
<li>Klik menu <em>Exploration</em> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <em>Descriptives</em></li>
<li>Periksa jumlah observasi per sel (<em>crosstabs</em>): <strong>N per sel harus sama</strong></li>
</ol>
<p><strong>Desain seimbang vs tidak seimbang:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th><em>Balanced</em></th>
<th><em>Unbalanced</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N per sel</td>
<td>Sama</td>
<td>Berbeda</td>
</tr>
<tr class="even">
<td>Analisis</td>
<td>Lebih mudah, SS ortogonal</td>
<td>Lebih kompleks — gunakan Tipe III SS</td>
</tr>
<tr class="odd">
<td>Interpretasi</td>
<td><em>Main effects</em> independen</td>
<td>Hati-hati pada interaksi</td>
</tr>
</tbody>
</table>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Pada studi Alfonso, setiap sel berisi <strong>N = 5 kucing</strong>, jadi desainnya <em>balanced</em>. Dalam studi <em>balanced</em>, efek jenis makanan dan jenis musik sepenuhnya <strong>ortogonal</strong> — estimasi satu efek tidak terpengaruh oleh efek yang lain.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="hipotesis-yang-diuji" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Hipotesis yang diuji</h1>

</section>
<section id="tiga-pengujian-hipotesis-sekaligus" class="slide level2">
<h2>Tiga pengujian hipotesis sekaligus</h2>
<p>ANOVA faktorial 2 faktor menguji <strong>tiga hipotesis</strong> secara bersamaan:</p>
<p><strong>1. Efek utama Faktor A (jenis makanan):</strong></p>
<p><span class="math display">\[H_0: \mu_{1\cdot} = \mu_{2\cdot} = \mu_{3\cdot}\]</span> <span class="math display">\[H_a: \text{setidaknya satu } \mu_{j\cdot} \text{ berbeda}\]</span></p>
<p><strong>2. Efek utama Faktor B (jenis musik):</strong></p>
<p><span class="math display">\[H_0: \mu_{\cdot1} = \mu_{\cdot2}\]</span> <span class="math display">\[H_a: \mu_{\cdot1} \neq \mu_{\cdot2}\]</span></p>
<p><strong>3. Efek interaksi A × B:</strong></p>
<p><span class="math display">\[H_0: \text{efek jenis makanan sama di semua level jenis musik (dan sebaliknya)}\]</span> <span class="math display">\[H_a: \text{efek jenis makanan bergantung pada level jenis musik}\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>Interaksi selalu diinterpretasikan terlebih dahulu.</strong> Jika interaksi signifikan, <em>main effects</em> tidak dapat diinterpretasikan secara independen — efek satu faktor berubah tergantung pada level faktor lain.</p>
</div>
</div>
</div>
</section>
<section id="main-effect-vs-interaction-effect" class="slide level2">
<h2><em>Main effect</em> vs <em>interaction effect</em></h2>
<p><strong>Efek utama (<em>main effect</em>):</strong> efek rata-rata satu faktor, <strong>dirata-rata</strong> di semua level faktor lain.</p>
<ul>
<li>Efek utama musik = perbedaan antara kolom klasik dan campursari, <strong>dirata-rata</strong> di semua jenis makanan</li>
<li>Efek utama makanan = perbedaan antara baris <em>dry</em>, <em>wet</em>, <em>raw food</em>, <strong>dirata-rata</strong> di semua jenis musik</li>
</ul>
<p><strong>Efek interaksi (<em>interaction effect</em>):</strong> efek satu faktor <strong>berubah</strong> tergantung pada level faktor lain.</p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Contoh interaksi: “Efek musik klasik pada durasi membaca lebih besar pada kucing yang diberi <em>wet food</em> dibanding <em>dry food</em>.”</p>
<p>Tanpa interaksi: “Efek musik klasik sama untuk semua jenis makanan.”</p>
</div>
</div>
</div>
</section>
<section id="mendeteksi-interaksi-secara-visual" class="slide level2">
<h2>Mendeteksi interaksi secara visual</h2>
<p>Cara termudah mendeteksi interaksi: lihat <strong>plot <em>estimated marginal means</em></strong></p>
<ul>
<li><strong>Tanpa interaksi</strong>: garis-garis pada plot <strong>sejajar</strong> (atau hampir sejajar)</li>
<li><strong>Dengan interaksi</strong>: garis-garis pada plot <strong>bersilangan</strong> atau saling menjauh</li>
</ul>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Tidak ada interaksi:</strong></p>
<p>Peningkatan durasi membaca akibat musik klasik <strong>sama</strong> untuk semua jenis makanan → garis sejajar</p>
</div><div class="column" style="width:50%;">
<p><strong>Ada interaksi:</strong></p>
<p>Peningkatan akibat musik klasik <strong>berbeda</strong> tergantung makanan → garis bersilangan atau mengembang</p>
</div></div>
<div class="callout callout-tip callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Tip</strong></p>
</div>
<div class="callout-content">
<p>Interaksi yang bersilangan (<em>crossover interaction</em>) lebih kuat secara interpretasi dibanding interaksi yang tidak bersilangan (<em>ordinal interaction</em>) karena arah efek berubah.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="partisi-varians-dalam-desain-faktorial" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Partisi varians dalam desain faktorial</h1>

</section>
<section id="dekomposisi-sum-of-squares" class="slide level2">
<h2>Dekomposisi <em>Sum of Squares</em></h2>
<p>Dalam ANOVA faktorial, total varians dipartisi menjadi empat komponen:</p>
<p><span class="math display">\[SS_{\text{tot}} = SS_A + SS_B + SS_{A \times B} + SS_{\text{within}}\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Sumber varians</th>
<th>Simbol</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Faktor A (makanan)</td>
<td><span class="math inline">\(SS_A\)</span></td>
<td>Variabilitas antar level makanan</td>
</tr>
<tr class="even">
<td>Faktor B (musik)</td>
<td><span class="math inline">\(SS_B\)</span></td>
<td>Variabilitas antar level musik</td>
</tr>
<tr class="odd">
<td>Interaksi A × B</td>
<td><span class="math inline">\(SS_{A \times B}\)</span></td>
<td>Variabilitas sel yang tidak dijelaskan <em>main effects</em></td>
</tr>
<tr class="even">
<td>Dalam sel (<em>within</em>)</td>
<td><span class="math inline">\(SS_w\)</span></td>
<td>Variabilitas individual dalam setiap sel</td>
</tr>
</tbody>
</table>
</section>
<section id="rasio-f-untuk-setiap-efek" class="slide level2">
<h2>Rasio F untuk setiap efek</h2>
<p>Setiap efek diuji dengan rasio F tersendiri menggunakan <span class="math inline">\(MS_w\)</span> yang sama sebagai penyebut:</p>
<p><span class="math display">\[F_A = \frac{MS_A}{MS_w}, \quad F_B = \frac{MS_B}{MS_w}, \quad F_{A \times B} = \frac{MS_{A \times B}}{MS_w}\]</span></p>
<p><strong>Degrees of freedom:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sumber</th>
<th>df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Faktor A (a level)</td>
<td><span class="math inline">\(a - 1\)</span></td>
</tr>
<tr class="even">
<td>Faktor B (b level)</td>
<td><span class="math inline">\(b - 1\)</span></td>
</tr>
<tr class="odd">
<td>Interaksi A × B</td>
<td><span class="math inline">\((a-1)(b-1)\)</span></td>
</tr>
<tr class="even">
<td>Dalam sel</td>
<td><span class="math inline">\(N - ab\)</span></td>
</tr>
<tr class="odd">
<td>Total</td>
<td><span class="math inline">\(N - 1\)</span></td>
</tr>
</tbody>
</table>
<p>Untuk desain 3 × 2 Alfonso dengan N = 30: <span class="math inline">\(df_A\)</span> = 2, <span class="math inline">\(df_B\)</span> = 1, <span class="math inline">\(df_{A\times B}\)</span> = 2, <span class="math inline">\(df_w\)</span> = 24.</p>
</section></section>
<section>
<section id="implementasi-di-jamovi" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Implementasi di jamovi</h1>

</section>
<section id="langkah-anova-faktorial-di-jamovi-main-effects-saja" class="slide level2">
<h2>Langkah ANOVA faktorial di jamovi: <em>main effects</em> saja</h2>
<p>Buka dataset <a href="..\docs/materials/kucing-membaca.omv"><strong>kucing-membaca.omv</strong></a>, kemudian:</p>
<ol type="1">
<li>Klik menu <em>ANOVA</em> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <strong><em>ANOVA</em></strong></li>
<li>Masukkan <strong>durasi_membaca</strong> ke <em>Dependent Variable</em></li>
<li>Masukkan <strong>jenis_makanan</strong> dan <strong>jenis_musik</strong> ke <em>Fixed Factors</em></li>
<li>Di menu <em>Model</em>, lihat kolom <em>Model Terms</em> — <strong>hapus</strong> suku interaksi <code>jenis_makanan*jenis_musik</code> untuk menguji <em>main effects</em> saja</li>
<li>Di opsi <em>Effect Size</em>, centang <strong>η²</strong> dan <strong>ω²</strong></li>
<li>Di opsi <em>Assumption Checks</em>, centang semua opsi</li>
</ol>
</section>
<section id="langkah-lanjutan-post-hoc-dan-marginal-means" class="slide level2">
<h2>Langkah lanjutan: <em>post-hoc</em> dan <em>marginal means</em></h2>
<ol start="7" type="1">
<li>Di opsi <em>Post-Hoc Tests</em>, masukkan <strong>jenis_makanan</strong> dan <strong>jenis_musik</strong> secara terpisah</li>
<li>Centang <em>Bonferroni</em> dan <em>Cohen’s d</em> serta <em>Confidence Interval</em> 95%</li>
<li>Di opsi <em>Estimated Marginal Means</em>:
<ul>
<li>Masukkan <strong>jenis_makanan</strong> ke <em>Terms 1</em></li>
<li>Klik <em>Add New Term</em>, masukkan <strong>jenis_musik</strong> ke <em>Terms 2</em></li>
</ul></li>
<li>Centang <em>Marginal means plot</em>, <em>Marginal means table</em>, dan <em>Observed scores</em></li>
</ol>
</section>
<section id="membaca-hasil-main-effects" class="slide level2">
<h2>Membaca hasil <em>main effects</em></h2>
<p><strong>Tabel ANOVA (tanpa interaksi):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sumber</th>
<th>F</th>
<th>df</th>
<th><em>p</em></th>
<th>ω²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>jenis_makanan</td>
<td>48.1</td>
<td>2, 24</td>
<td>&lt; .001</td>
<td>0.553</td>
</tr>
<tr class="even">
<td>jenis_musik</td>
<td>9.83</td>
<td>1, 24</td>
<td>.004</td>
<td>0.108</td>
</tr>
<tr class="odd">
<td>Residuals</td>
<td>—</td>
<td>24</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Interpretasi:</strong></p>
<ul>
<li>Jenis makanan berpengaruh signifikan pada durasi membaca, <em>F</em>(2, 24) = 48.1, <em>p</em> &lt; .001, ω² = 0.553 — efek besar</li>
<li>Jenis musik berpengaruh signifikan, <em>F</em>(1, 24) = 9.83, <em>p</em> = .004, ω² = 0.108 — efek sedang</li>
</ul>
</section>
<section id="menguji-efek-interaksi-di-jamovi" class="slide level2">
<h2>Menguji efek interaksi di <code>jamovi</code></h2>
<p>Untuk menguji interaksi, <strong>jangan</strong> hapus suku interaksi di menu <em>Model</em>:</p>
<ol type="1">
<li>Kembali ke menu <em>Model</em> — pastikan <code>jenis_makanan*jenis_musik</code> <strong>tetap ada</strong> di <em>Model Terms</em></li>
<li>Di opsi <em>Estimated Marginal Means</em>, masukkan <strong>jenis_makanan</strong> dan <strong>jenis_musik</strong> ke <strong><em>Terms 1 yang sama</em></strong> (bukan dua <em>Terms</em> terpisah)</li>
<li>Centang <em>Marginal means plot</em> — perhatikan apakah garis-garis sejajar atau bersilangan</li>
</ol>
<p><strong>Interpretasi tabel ANOVA dengan interaksi:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Sumber</th>
<th>F</th>
<th>df</th>
<th><em>p</em></th>
<th>ω²</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>jenis_makanan</td>
<td>44.9</td>
<td>2, 24</td>
<td>&lt; .001</td>
<td>0.527</td>
</tr>
<tr class="even">
<td>jenis_musik</td>
<td>9.17</td>
<td>1, 24</td>
<td>.006</td>
<td>0.101</td>
</tr>
<tr class="odd">
<td>jenis_makanan × jenis_musik</td>
<td>3.12</td>
<td>2, 24</td>
<td>.063</td>
<td>0.050</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>—</td>
<td>24</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
<p>Interaksi: <em>F</em>(2, 24) = 3.12, <em>p</em> = .063 — <strong>tidak signifikan</strong> pada α = 0.05. <em>Main effects</em> dapat diinterpretasikan secara independen.</p>
</section></section>
<section>
<section id="effect-size-untuk-anova-faktorial" class="title-slide slide level1 center" data-background-color="#14497F">
<h1><em>Effect size</em> untuk ANOVA faktorial</h1>

</section>
<section id="partial-η²-dan-ω²" class="slide level2">
<h2>Partial η² dan ω²</h2>
<p>Dalam ANOVA faktorial, umumnya dilaporkan <strong><em>partial</em> η²</strong> (bukan η² total) karena ia mengukur proporsi varians yang dijelaskan oleh satu efek <strong>setelah mempartisi efek lain</strong>:</p>
<p><span class="math display">\[\eta^2_p = \frac{SS_{\text{efek}}}{SS_{\text{efek}} + SS_w}\]</span></p>
<p><span class="math display">\[\omega^2_p \approx \frac{SS_{\text{efek}} - df_{\text{efek}} \cdot MS_w}{SS_{\text{efek}} + SS_w + MS_w}\]</span></p>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p><strong>η² total vs <em>partial</em> η²:</strong> η² total membagi <span class="math inline">\(SS_{\text{efek}}\)</span> dengan <span class="math inline">\(SS_{\text{tot}}\)</span> — nilainya lebih kecil dan seluruh efek menjumlahkan ke 1 (atau kurang). <em>Partial</em> η² masing-masing efek bisa menjumlahkan melebihi 1, tetapi lebih mudah dibandingkan dengan konvensi Cohen (<em>kecil</em>: .01, <em>sedang</em>: .06, <em>besar</em>: .14).</p>
</div>
</div>
</div>
</section>
<section id="konvensi-effect-size-untuk-anova" class="slide level2">
<h2>Konvensi <em>effect size</em> untuk ANOVA</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>ω² (atau η²)</th>
<th>Interpretasi</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.01</td>
<td>Efek kecil</td>
</tr>
<tr class="even">
<td>0.06</td>
<td>Efek sedang</td>
</tr>
<tr class="odd">
<td>0.14</td>
<td>Efek besar</td>
</tr>
</tbody>
</table>
<p>Pada studi Alfonso:</p>
<ul>
<li>Jenis makanan: ω² = 0.527 → <strong>efek yang sangat besar</strong></li>
<li>Jenis musik: ω² = 0.101 → <strong>efek sedang</strong></li>
<li>Interaksi: ω² = 0.050 → <strong>efek kecil</strong> (dan tidak signifikan)</li>
</ul>
</section></section>
<section>
<section id="post-hoc-tests" class="title-slide slide level1 center" data-background-color="#14497F">
<h1><em>Post-hoc tests</em></h1>

</section>
<section id="kapan-post-hoc-test-diperlukan" class="slide level2">
<h2>Kapan <em>post-hoc test</em> diperlukan?</h2>
<p><em>Post-hoc test</em> diperlukan untuk faktor dengan <strong>lebih dari 2 level</strong> yang signifikan, untuk mengidentifikasi pasangan kelompok mana yang berbeda.</p>
<ul>
<li><strong>Jenis makanan</strong> (3 level, signifikan) → perlu <em>post-hoc</em></li>
<li><strong>Jenis musik</strong> (2 level, signifikan) → <strong>tidak perlu</strong> <em>post-hoc</em>, karena hanya ada satu perbandingan (klasik vs campursari)</li>
<li><strong>Interaksi</strong> (tidak signifikan) → tidak perlu <em>simple effects</em> analysis</li>
</ul>
</section>
<section id="hasil-post-hoc-jenis-makanan-bonferroni" class="slide level2">
<h2>Hasil <em>post-hoc</em> jenis makanan (Bonferroni)</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Perbandingan</th>
<th>Perbedaan <em>mean</em></th>
<th>SE</th>
<th>Cohen’s <em>d</em></th>
<th><em>p</em> (Bonferroni)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Dry food</em> vs <em>Wet food</em></td>
<td>−0.267</td>
<td>0.143</td>
<td>−0.597</td>
<td>.186</td>
</tr>
<tr class="even">
<td><em>Dry food</em> vs <em>Raw food</em></td>
<td><strong>−1.033</strong></td>
<td>0.143</td>
<td><strong>−2.311</strong></td>
<td><strong>&lt; .001</strong></td>
</tr>
<tr class="odd">
<td><em>Wet food</em> vs <em>Raw food</em></td>
<td><strong>−0.767</strong></td>
<td>0.143</td>
<td><strong>−1.714</strong></td>
<td><strong>&lt; .001</strong></td>
</tr>
</tbody>
</table>
<p><strong>Interpretasi:</strong></p>
<ul>
<li><em>Dry food</em> dan <em>wet food</em> tidak berbeda secara signifikan (<em>p</em> = .186)</li>
<li><em>Raw food</em> menghasilkan durasi membaca yang secara signifikan lebih lama dibanding <em>dry food</em> dan <em>wet food</em> (keduanya <em>p</em> &lt; .001)</li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Jika interaksi signifikan, lakukan <strong><em>simple effects analysis</em></strong> (analisis efek satu faktor pada setiap level faktor lain) alih-alih <em>post-hoc</em> biasa. Ini bisa dilakukan di jamovi via menu <em>Simple Effects</em>.</p>
</div>
</div>
</div>
</section></section>
<section>
<section id="asumsi-anova-faktorial" class="title-slide slide level1 center" data-background-color="#14497F">
<h1>Asumsi ANOVA faktorial</h1>

</section>
<section id="asumsi-yang-harus-dipenuhi" class="slide level2">
<h2>Asumsi yang harus dipenuhi</h2>
<p>ANOVA faktorial mewarisi asumsi ANOVA satu jalur dengan tambahan pertimbangan desain:</p>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Asumsi</th>
<th>Cara memeriksa</th>
<th>Catatan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Normalitas residual</strong></td>
<td>Q-Q plot residual</td>
<td>Robust jika N per sel ≥ 20</td>
</tr>
<tr class="even">
<td><strong>Homogenitas varians</strong></td>
<td>Levene’s test</td>
<td>Periksa per sel, bukan per faktor saja</td>
</tr>
<tr class="odd">
<td><strong>Independensi observasi</strong></td>
<td>Desain penelitian</td>
<td>Sangat serius jika dilanggar</td>
</tr>
<tr class="even">
<td><strong>Desain seimbang</strong></td>
<td>Crosstabs N per sel</td>
<td>Jika tidak seimbang, gunakan Tipe III SS</td>
</tr>
</tbody>
</table>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Important</strong></p>
</div>
<div class="callout-content">
<p>Dalam desain <strong>tidak seimbang</strong> (<em>unbalanced</em>), perbedaan antara <em>Type I</em>, <em>Type II</em>, dan <em>Type III Sum of Squares</em> menjadi krusial. jamovi secara <em>default</em> menggunakan <strong>Tipe III SS</strong> — yang tepat untuk hampir semua kasus dengan desain tidak seimbang.</p>
</div>
</div>
</div>
</section>
<section id="memeriksa-homogenitas-varians-di-jamovi" class="slide level2">
<h2>Memeriksa homogenitas varians di jamovi</h2>
<p>Levene’s test dalam ANOVA faktorial memeriksa homogenitas varians <strong>di semua sel</strong> (6 sel untuk desain 3 × 2), bukan hanya per faktor.</p>
<p>Pada studi Alfonso:</p>
<ul>
<li>Levene’s <em>F</em>(5, 24) = 1.38, <em>p</em> = .270 → <strong>asumsi homogenitas terpenuhi</strong></li>
</ul>
<p>Jika Levene’s signifikan:</p>
<ul>
<li>Interpretasi hasil dengan hati-hati</li>
<li>Pertimbangkan transformasi data (log, akar kuadrat)</li>
<li>Atau gunakan analisis alternatif yang robust terhadap heterogenitas varians</li>
</ul>
</section></section>
<section>
<section id="a-priori-analisis-power" class="title-slide slide level1 center" data-background-color="#14497F">
<h1><em>A priori</em> analisis <em>power</em></h1>

</section>
<section id="menggunakan-pangea-untuk-desain-faktorial" class="slide level2">
<h2>Menggunakan PANGEA untuk desain faktorial</h2>
<p>Untuk ANOVA faktorial, gunakan <strong>PANGEA</strong> (<em>Power ANalysis for GEneral Anova designs</em>) — aplikasi <em>online</em> yang lebih fleksibel dari G*Power untuk desain kompleks.</p>
<p><strong>Akses:</strong> <a href="https://jakewestfall.shinyapps.io/pangea/">jakewestfall.shinyapps.io/pangea/</a></p>
<p><strong>Atau gunakan G*Power:</strong></p>
<ol type="1">
<li><em>Test family</em> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <strong><em>F</em> tests</strong></li>
<li><em>Statistical test</em> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <em>ANOVA: Fixed effects, main effects and interactions</em></li>
<li><em>Type of power analysis</em> <i class="fa-solid fa-circle-arrow-right" aria-label="circle-arrow-right"></i> <strong><em>A priori</em></strong></li>
</ol>
</section>
<section id="contoh-power-untuk-studi-alfonso-lanjutan" class="slide level2">
<h2>Contoh: <em>power</em> untuk studi Alfonso lanjutan</h2>
<p>Alfonso ingin meneliti efek <strong>pemberian vitamin</strong> (Vitamin A, B, C, atau tanpa vitamin — 4 level) dan <strong>pemberian vaksin</strong> (divaksin vs tidak — 2 level) pada jumlah bulu kucing yang rontok.</p>
<p><strong>Parameter:</strong></p>
<ul>
<li><em>Effect size f</em> = 0.15 (efek kecil, ia tidak terlalu yakin)</li>
<li>α = 0.05, <em>Power</em> = 0.90 (<span class="math inline">\(\beta\)</span> = 0.10)</li>
<li>Jumlah kelompok = 4 × 2 = <strong>8 sel</strong></li>
</ul>
<p><strong>Di G*Power:</strong></p>
<p>Masukkan <em>Number of groups</em> = 8, <em>Effect size f</em> = 0.15, α = 0.05, <em>Power</em> = 0.90</p>
<p><strong>Hasil: N total ≈ 440 (55 per sel)</strong></p>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<p>Desain faktorial membutuhkan sampel yang lebih besar karena jumlah sel meningkat secara multiplikatif. Pertimbangkan apakah interaksi benar-benar diperlukan — jika tidak, desain satu faktor mungkin lebih efisien.</p>
</div>
</div>
</div>
</section>
<section id="latihan-analisis-anova-faktorial" class="slide level2">
<h2>Latihan: analisis ANOVA faktorial</h2>
<p>Seorang peneliti ingin menguji pengaruh <strong>metode belajar</strong> (ceramah, diskusi, <em>flipped classroom</em>) dan <strong>waktu belajar</strong> (pagi vs sore) terhadap <strong>nilai ujian</strong> mahasiswa.</p>
<ol type="1">
<li>Buka dataset <strong>nilai-ujian.omv</strong> dan jalankan ANOVA faktorial 3 × 2</li>
<li>Periksa desain: apakah <em>balanced</em>? Buat <em>crosstabs</em></li>
<li>Uji interaksi terlebih dahulu — apakah signifikan?</li>
<li>Jika tidak signifikan, interpretasikan <em>main effects</em> secara independen</li>
<li>Jalankan <em>post-hoc test</em> Bonferroni untuk faktor yang memiliki &gt; 2 level dan signifikan</li>
<li>Buat <em>estimated marginal means plot</em> — apakah garis-garisnya sejajar?</li>
</ol>
<p>Pertanyaan untuk didiskusikan:</p>
<ul>
<li>Apa artinya jika interaksi signifikan dalam konteks ini?</li>
<li>Kapan <em>simple effects analysis</em> lebih tepat daripada <em>main effects</em> saja?</li>
<li>Bagaimana melaporkan hasil ANOVA faktorial dalam APA format?</li>
</ul>
</section>
<section id="ada-pertanyaan" class="slide level2">
<h2>Ada pertanyaan❓</h2>

<img data-src="https://media3.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDFtaDh5ZjZ2eXJ3dmJmZmFmYzBtNHEwdzlqZmZtdGtmbnE0bXZidiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/igB2Th9e4nW6s/giphy.gif" class="quarto-figure quarto-figure-center r-stretch"><div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Note</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Paparan disusun dengan menggunakan <i class="fa-brands fa-r-project"></i> dan <a href="https://quarto.org"><strong>Quarto</strong></a> dengan <em>template</em> dari <a href="https://github.com/rameliaz/quarto-unair-theme">UNAIR Theme</a>.</li>
<li>Kontak saya via <i class="fas fa-paper-plane"></i> <a href="mailto:amelia.zein@psikologi.unair.ac.id">amelia.zein@psikologi.unair.ac.id</a></li>
</ul>
</div>
</div>
</div>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>
    // Single unified function to manage all logos
    function manageLogos() {
      const slides = document.querySelectorAll('.reveal .slides section');
      
      slides.forEach(function(slide, index) {
        // Handle title slide (first slide)
        if (index === 0) {
          // Remove any regular logos from title slide
          const regularLogos = slide.querySelectorAll('.slide-logo');
          regularLogos.forEach(logo => logo.remove());
          
          // Add centered logo if it doesn't exist
          if (!slide.querySelector('.title-slide-logo')) {
            const titleLogo = document.createElement('img');
            titleLogo.src = '../img/logo.png';
            titleLogo.className = 'title-slide-logo';
            titleLogo.alt = 'Universitas Airlangga Logo';
            slide.insertBefore(titleLogo, slide.firstChild);
          }
          return;
        }
        
        // For all other slides, ensure only ONE logo exists
        const existingLogos = slide.querySelectorAll('.slide-logo');
        
        // If multiple logos exist, remove all and start fresh
        if (existingLogos.length > 1) {
          existingLogos.forEach(logo => logo.remove());
        }
        
        // Check background color
        const bgColor = slide.getAttribute('data-background-color');
        const logoSrc = (bgColor === '#14497F' || bgColor === '#14497f') 
          ? '../img/logo_white.png'
          : '../img/logo.png';
        
        // If exactly one logo exists, just update its source
        if (existingLogos.length === 1) {
          existingLogos[0].src = logoSrc;
        } 
        // If no logo exists, create one
        else if (existingLogos.length === 0) {
          const logo = document.createElement('img');
          logo.src = logoSrc;
          logo.className = 'slide-logo';
          logo.alt = 'Universitas Airlangga Logo';
          slide.appendChild(logo);
        }
      });
    }

    // Initialize on page load
    document.addEventListener('DOMContentLoaded', function() {
      if (typeof Reveal !== 'undefined') {
        Reveal.on('ready', function() {
          manageLogos();
        });
      } else {
        setTimeout(manageLogos, 500);
      }
    });

    // Update when slides change
    if (typeof Reveal !== 'undefined') {
      Reveal.on('slidechanged', function() {
        manageLogos();
      });
    }
    </script>

    <style>
    /* Additional inline styles for logo */
    .reveal .slide-logo {
      position: absolute !important;
      top: -1em !important;  /* Aligns with title */
      right: 15px !important;
      max-height: 80px !important;
      max-width: 200px !important;
      z-index: 100 !important;
      object-fit: contain;
    }

    /* Ensure title slide doesn't have logo overlap */
    .reveal .title-slide {
      padding-right: 220px;
    }

    /* Section title slide styling */
    .reveal section[data-background-color] h1,
    .reveal section[data-background-color] h2 {
      color: white !important;
    }
    </style>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>